### ISSUE TITLE
Header action item texts are not centered when i18n is Hindi

### ISSUE THREAD

**Issue by ArfatSalman** [pesto-students/little-tags-client#30]
![Screenshot 2021-03-07 at 6 32 35 PM](https://user-images.githubusercontent.com/10287217/110240780-838db180-7f73-11eb-85b2-0a38e7425715.png)

Any reason why the Hindi text is not centered? The English one is, though. 

![Screenshot 2021-03-07 at 6 33 24 PM](https://user-images.githubusercontent.com/10287217/110240800-9b653580-7f73-11eb-9391-840a1fe747d8.png)

**Comment by AamirAlam** [comment]
Fixed in #29
