### ISSUE TITLE
Implement the Landing Page + Login / Signup page

### ISSUE THREAD

**Issue by ArfatSalman** [pesto-students/little-tags-client#4]
# Instructions

As per your mocks, implement the landing page and deploy it. The products / cart / wishlist buttons do not have to work as of now. Just the landing page (+ some other things) are required. Here's a list of concrete requirements.

## Requirements

- [x] Landing Page (as per the mocks)
  - [x] Desktop version
  - [x] Mobile version
- [x] Login / Signup Modal or individual page.
- [x] Internationalization Support. There should be a way to change the language and see (at the very least) different texts for the words "login" and "signup".  
       _(If both you and your partner do not speak a second language, you can use Spanish as a second language. You can verify the translations with me.)_

Once you are done with the implementations, paste screenshots of your **actual** running websites with your mocks side by side (like [this](https://i.imgur.com/RKhJ0Jx.png)) in a comment. The left side is will be your mock, and the right side will be your actual implementation. Ensure that the resolutions of both the parts are same (or similar) to help with faster comparison.

## Resources

- For creating custom flex layouts: [Link](https://tobiasahlin.com/blog/common-flexbox-patterns/)
- _Book_ Responsive Web Design by **Ethan Marcotte**. You can find this book somewhere on the internet. You can search for it. Ethan _**coined**_ the term and create "responsive design" patterns. This book (under 200 pages) is a great read for understanding what responsiveness means. You can buy it as well if you like it. [Link](https://abookapart.com/products/responsive-web-design)
- React Internationalization. Slightly old but still a comprehensive starter resource: [Link](https://www.smashingmagazine.com/2017/01/internationalizing-react-apps/)
- React Internationalization using a different library (`react-i18next`). [Link](https://www.robinwieruch.de/react-internationalization)
- Try to use the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) Web API for rendering the prices, plurals, etc.

_Pro tip:_ You can create multiple PRs that closes the same issue. There doesn't have to be one-to-one relationship between an issue and a PR. So feel free to open multiple PRs against this issue.

Comment on this issue if you need help with anything.

**Comment by AamirAlam** [comment]
Implemented all the requirements specified in this issue.
